# Generated by Django 5.0.6 on 2025-01-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='birth_date',
            new_name='birth_day',
        ),
    ]
